### ISSUE TITLE
missing library unirest and problem with import statement

### ISSUE THREAD

**Issue by ThaBrad** [evgenTraytyak/kiwi-api#1]
After inspecting errors further, now I understood the first error (that I was starting to describe below).

So easy fix: `npm install unirest -save`, but obviously that's not enough. 

Somehow it keeps rejecting the import statement, although I have Node 8.9 installed :-/, but I guess this on is on me.

Appreciate the help

----------------------------------------------------------------
----------------------------------------------------------------

Executing the import statement `import KiwiAPI from 'kiwi-api';` immediately triggers an **error:**
```
(function (exports, require, module, __filename, __dirname) { import KiwiAPI from 'kiwi-api';
                                                                                                       ^^^^^^
SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Or if I compile it first as a typescript file:**
```
module.js:538
    throw err;
    ^
Error: Cannot find module 'unirest'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/davidpanholzer/Desktop/Kiwi node/node_modules/kiwi-api/build/index.js:9:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Further checking with this out with the debugger:
(node engine) `var filename = Module._findPath(request, paths, isMain);`
The first time it runs with `request = kiwi-api`, the second time `unrest`, which is not found anymore leading the following if `(filename = false)` statement to throw an error.

**Comment by ThaBrad** [comment]
Ok, the package and transpiling it now again with typescript (Babel would prob also work just fine).

Now it's working
